language: python
virtualenv:
  system_site_packages: true
env:
  global:
    - LD_PRELOAD=/usr/lib/x86_64-linux-gnu/libgfortran.so.3
  matrix:
    - DISTRIB="conda" PYTHON_VERSION="2.7" INSTALL_ATLAS="true"
      NUMPY_VERSION="1.10.4" SCIPY_VERSION="0.17.0"
      COVERAGE="true" INSTALL_GLPK="false"
sudo: required
install: source continuous_integration/install.sh
script:
  - bash continuous_integration/test_script.sh
after_success:
    - if [[ "$COVERAGE" == "true" ]]; then coveralls; fi
addons:
  apt:
    packages:
    - gfortran
    - libgfortran3

before_deploy:
  # Create wheel
  - pip wheel -w wheel .
  - mkdir wheel/dist/ && mv wheel/cvxpy* wheel/dist/

# Upload master wheels to S3 for pypicloud
deploy:
  provider: s3
  access_key_id:
    secure: "eT3LH3VxHD+4hCbg4yOqRYCf0sEme00Dg9N2nJPHD/a4WeYvN59F0lpXB3D3fRMubGdukBo2lza1Ql6xKDL9YI/rsSRAcTIC1JgirxqvxLg1HXwaaOML+2rytj2vYhlDYnfM2joILAqgB4HqukaFgV7x5n8ZMNDpBgmcUp+FO66dh/hK/JQz1RppCyLrFoDmS8hjXJvQ5jlnMlOcN0hy2YtZdtgfafTwsab0fVGfKR0kD24bnqWnpNouCFIXaIg1NZj8mNRc8nfiopWHFJNnRa0q63vgeH2YXPIYjck5EC4f3cEVVx3gkvThw2jKye3hgUQQSlf0bWPqinJNw6hFGbZbmjxqN0HvwScUtZBOzz1Tuu+IAK4pQqqKP3Md2vM8ob3N+II62l0r1+5Ebk65vS4RiFQjBVe9qzfdweUS5vwEsPkKmnrRTQLGCi6C0yNVwec1ObynekhwfUA3U2+bupxl+jWGfJO9V/y1THpXmZl2COgl6mn7VO6ootypxHvI7wtp9MXrgxzeKUDuk7lp9Kc0kH9mfYyLrcr5C++Ec7DjnB7OYzOIstPxblH7CfGldM2aHjcXFokk/6AO3zhCkKLSnFiB9L8oyYR1ebJZnN+btWn6EDQccPqYaohq4SHHXSyUn+dYcWfMM3VuJi2g8Ho4m3wl9twKldJoVR4kUc8="
  secret_access_key:
    secure: "ExyhgMGcz8E4rq3Eu4/olD3JAH1KWz9j8f1Bqq2qDfzs0HA7uhi29f3JR4BJ1WOGQoqSUA5wSN4Y3g3FrFxkIpxgv05bZ4dxEbJ3aFb6aczAAUudpmh3SxF00GpglSKYxkfz0BPnLyWEQgJcxHRBECMExBf3TzICuSjfF9DynuQwrVZmTXFKMqqPS/2kY8ACAHXeeqYBXS3Kq+OO2GO5wqQOAyc4NiQKVef1UqfGqfJ6cbFyfqqjWYkKi3cUM5IXVEL9Ni/ir8Gn12F9eNRdfT8t1a1zmhLY+57AyHZIuUiIL4dm8eT6fLjenRBukrMxbZYMmTMR9k8dTVIo7Jgu+6RG4tc1Rq9RHlLsDdcZqJjW6qxIx9vUM8EHgJlLdcNOOwfiNd7MRXmQ2EzXWHvTXp+K3SUDB4CDqV9dsNZWk5RinrxzJ98YryaDe4ncsu+KH2cHdJMmBXTv6+bpZblKIh6b2xaVctTEDdFJn0Xi+OYx+s4GGnavTBTLTEh1Co/Kc+/8c5Orv359QTLVNtjLae3ZFNfFd2v1twY0aeqYA7V7fvx8vTy9z/rTVuJQL0qv5s6g5k2P/v0dx93tbTEpGTIF3toetuvoi45m/0HuXq0AKQAAIqwGpeCCPHzP4JUkP2Zyl5J06lNUBa18+dLRENE5jNfpRZoQrAxwwtfCNPM="
  bucket: software-buildingrobotics
  local-dir: wheel/dist
  upload-dir: cvxpy
  region: us-west-1
  skip_cleanup: true
  on:
    repo: BuildingRobotics/cvxpy
    branch: Comfy/master
